spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  profiles:
    active: local
    include: secret

  servlet.multipart.max-file-size: 5MB
  servlet.multipart.max-request-size: 5MB

jwt:
  key:
    access: base64 인코딩된 key
    refresh: base64 인코딩된 key
  max-age:
    access: 1800 # 60 * 30
    refresh: 604800 # 60 * 60 * 24 * 7


